name: Build ale

on:
  push:
    tags-ignore:
      - "*.*"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  presubmit:
    name: Presubmit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/presubmit.sh

  build:
    name: Build ale on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: presubmit
    env:
      VCPKG_DEFAULT_TRIPLET: "x64-windows"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install Python dependencies
      run: |
        python -m pip install numpy pytest cmake
    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-2.0-0
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install sdl2
    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        vcpkg install zlib:${env:VCPKG_DEFAULT_TRIPLET} `
                      sdl2:${env:VCPKG_DEFAULT_TRIPLET} `
                      dlfcn-win32:${env:VCPKG_DEFAULT_TRIPLET}
        echo "$env:VCPKG_INSTALLATION_ROOT\installed\$env:VCPKG_DEFAULT_TRIPLET\bin" >> ${env:GITHUB_PATH}
    - name: Configure ale
      run: |
        mkdir build; cd build
        cmake ../ -DSDL_SUPPORT=ON -DPython3_FIND_FRAMEWORK=NEVER
    - name: Build ale
      working-directory: ./build
      run: |
        cmake --build . --config Debug --parallel 2
    - name: Test ale
      working-directory: ./build
      run: |
        ctest -C Debug --progress -VV
